#THIS DOCKERFILE IS FOR DEVELOPMENT STAGE
FROM node:14-alpine

RUN apk update

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY src /app/src

RUN ls -a

RUN yarn install

EXPOSE 3000

CMD ["yarn", "start:dev"]