#THIS DOCKERFILE IS FOR PRODUCTION STAGE

FROM node:12-alpine

RUN apk update

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY src /app/src

RUN ls -a

RUN yarn install
RUN yarn run build

EXPOSE 3000

CMD ["node", "./bin/index.js"]